"""
make_missionoptions_python.py
=============================
This file contains the make_PyEMTG_MissionOptions function.

"""

def make_PyEMTG_MissionOptions(OptionsDefinitions, now, path = '.'):
    """
    Function for automatically creating a MissionOptions.py file based on a csv of mission options.

    Parameters
    ----------
    OptionsDefinitions : List of dict entries
        Dict entries that define the options to be added to MissionOptions.py
    now : string
        A string of the current time.
    path : string, optional
        Path to directory in which to write MissionOptions.py. The default is '.'

    Returns
    -------
    None.

    """
    adaptive_integrator_options = {
        'integratorType', 'integrator_tolerance', 'integrator_error_control_mode',
        'integrator_relative_tolerance', 'integrator_absolute_tolerance_position',
        'integrator_absolute_tolerance_velocity', 'integrator_absolute_tolerance_mass',
        'integrator_absolute_tolerance_time', 'integrator_absolute_tolerance_other',
        'integrator_stm_error_control', 'integrator_stm_relative_tolerance',
        'integrator_stm_absolute_tolerance', 'integration_time_step_size',
        'integrator_initial_step_size', 'integrator_minimum_step_size',
        'integrator_safety_factor', 'integrator_minimum_step_scale',
        'integrator_maximum_step_scale', 'integrator_rejection_limit',
    }

    with open(path + "PyEMTG/MissionOptions.py", "w") as file:
        file.write('"""\n')
        file.write('MissionOptions.py\n')
        file.write('========================\n')
        file.write('auto-generated by make_EMTG_missionoptions_journeyoptions.py\n')
        file.write('\n')
        file.write('"""')
        file.write('\n')
        file.write('import ast\n')
        file.write('\n')
        file.write('try:\n')
        file.write('    from . import JourneyOptions\n')
        file.write('except ImportError:  # historical scripts import MissionOptions as a top-level module\n')
        file.write('    import JourneyOptions\n')
        file.write('\n')
        file.write('\n')
        file.write('def _parse_user_data(text):\n')
        file.write('    entries = []\n')
        file.write('    start = 0\n')
        file.write('    depth = 0\n')
        file.write('    quote = None\n')
        file.write('    escaped = False\n')
        file.write('    for index, character in enumerate(text):\n')
        file.write('        if escaped:\n')
        file.write('            escaped = False\n')
        file.write('            continue\n')
        file.write('        if character == "\\\\" and quote is not None:\n')
        file.write('            escaped = True\n')
        file.write('            continue\n')
        file.write('        if quote is not None:\n')
        file.write('            if character == quote:\n')
        file.write('                quote = None\n')
        file.write('            continue\n')
        file.write('        if character in {"\'", \'"\'}:\n')
        file.write('            quote = character\n')
        file.write('        elif character in "([{" :\n')
        file.write('            depth += 1\n')
        file.write('        elif character in ")]}":\n')
        file.write('            depth -= 1\n')
        file.write('        elif character == ":" and depth == 0:\n')
        file.write('            entries.append(text[start:index])\n')
        file.write('            start = index + 1\n')
        file.write('    if text[start:].strip():\n')
        file.write('        entries.append(text[start:])\n')
        file.write('    output = {}\n')
        file.write('    for entry in entries:\n')
        file.write('        pair = ast.literal_eval(entry.strip())\n')
        file.write('        if not isinstance(pair, tuple) or len(pair) != 2 or not isinstance(pair[0], str):\n')
        file.write('            raise ValueError("user_data entries must be (string, literal) pairs")\n')
        file.write('        output[pair[0]] = pair[1]\n')
        file.write('    return output\n')
        file.write('\n')

        file.write('class MissionOptions(object):\n')
        file.write('\n')

        tab = '    '
        file.write(tab + '"""\n') # start np-style comment block
        file.write('\n')
        file.write(tab + "MissionOptions class is used to read/write .emtgopt files and hold mission option variables.\n")
        
        file.write('\n')
        file.write(tab + '"""\n') # end np-style comment block

        aliases = {
            alias.strip(): option['name']
            for option in OptionsDefinitions
            for alias in option.get('aliases', '').split('|')
            if alias.strip()
        }
        file.write('    _OPTION_ALIASES = ' + repr(aliases) + '\n')
        file.write('\n')
        file.write('    def __setattr__(self, name, value):\n')
        file.write('        object.__setattr__(self, self._OPTION_ALIASES.get(name, name), value)\n')
        file.write('\n')
        file.write('    def __getattr__(self, name):\n')
        file.write('        canonical_name = self._OPTION_ALIASES.get(name)\n')
        file.write('        if canonical_name is not None:\n')
        file.write('            return object.__getattribute__(self, canonical_name)\n')
        file.write('        raise AttributeError(name)\n')
        file.write('\n')

        file.write('    #************************************************************************************constructor\n')
        file.write('    def __init__(self, optionsFileName = None):\n')

        for option in OptionsDefinitions:
            if option['name'] == 'user_data':
                #file.write('        self.' + option['name'] + ' = {} #' + option['comment'] + '\n')
                file.write('        self.' + option['name'] + ' = {}\n')
                file.write(tab + tab + '"""' + option['comment'] + '"""\n')
            elif 'string' in option['dataType']:
                file.write('        self.' + option['name'] + ' = "' + str(option['defaultValue']) + '"\n')
                file.write(tab + tab + '"""' + option['comment'] + '"""\n')
            else:
                file.write('        self.' + option['name'] + ' = ' + str(option['defaultValue']) + '\n')
                file.write(tab + tab + '"""' + option['comment'] + '"""\n')
            
        file.write('        \n')    
        file.write('        #empty master decision and constraint vectors - these exist only for interface with PyEMTG GUI and PEATSA\n')
        file.write('        self.trialX = []\n')
        file.write('        self.ManeuverConstraintDefinitions = []\n')
        file.write('        self.BoundaryConstraintDefinitions = []\n')
        file.write('        self.PhaseDistanceConstraintDefinitions = []\n')
        file.write('        \n')
        file.write('        if optionsFileName == None:\n')
        file.write('            self.Journeys = [JourneyOptions.JourneyOptions()]\n')
        file.write('            self.number_of_journeys = 1\n')
        file.write('        else:\n')
        file.write('            self.Journeys = []\n')
        file.write('            self.parse_mission(optionsFileName)\n')
        file.write('        self.filename = ""\n')
        file.write('        self.success = 1\n')
        file.write('        self.ActiveJourney = 0\n')
        file.write('        self.AU = 1.49597870691e+8\n')
        file.write('        self.G = 6.674280000000000367e-20\n')
        file.write('        self.g0 = 9.806649999999999423\n')
        file.write('        \n')

        file.write('   \n')
        file.write('    #************************************************************************************parse\n')
        file.write('    def parse_mission(self, optionsFileName):\n')
        file.write('        self.filename = optionsFileName.replace("\\ufeff", "")\n')
        file.write('        \n')
        file.write('        inputFile = []\n')
        file.write('        lineNumber = 0\n')
        file.write('        from os.path import isfile\n')
        file.write('        if isfile(self.filename):\n')
        file.write('            inputFile = open(self.filename, "r")\n')
        file.write('            self.success = 1\n')
        file.write('        else:\n')
        file.write('            print("Python is unable to open", self.filename)\n')
        file.write('            return\n')
        file.write('        \n')
        file.write('        while True:\n')
        file.write('            line = inputFile.readline()\n')
        file.write('            if not line:\n')
        file.write('                break\n')
        file.write('            #strip off the newline character\n')
        file.write('            line = line.rstrip("\\n\\r ")\n')
        file.write('            \n')
        file.write('            lineNumber += 1\n')
        file.write('            \n')
        file.write('            #if we got this far, then this is a line worth reading\n')
        file.write('            #Note that unlike EMTG proper, PyEMTG does NOT length or bounds-check input files. But if you try to run an invalid .emtgopt, EMTG will notify you and help you fix it.\n')
        file.write('            \n')
        file.write('            if line.strip(\'\\r\') != "":\n')
        file.write('                if line[0] != "#":\n')
        file.write('                    #this is an active line, so it is space delimited\n')
        file.write('                    linecell = [entry.rstrip(" \\r\\n") for entry in line.split(" ")]\n')
        file.write('                    \n')

        ifelse = ''
        for option in OptionsDefinitions:
            length = 1
            if 'std::vector' in option['dataType']:
                length = len(option['defaultValue'])
            converter_in = ''
            converter_out = ''

            if 'double' in option['dataType']:
                converter_in = 'float('
                converter_out = ')'
            elif 'string' not in option['dataType']:#bool, size_t, int, time_t, or any enum
                converter_in = 'int('
                converter_out = ')'
            
            
            accepted_names = [option['name']] + [alias.strip() for alias in option.get('aliases', '').split('|') if alias.strip()]
            if len(accepted_names) == 1:
                file.write('                    ' + ifelse + 'if linecell[0] == "' + option['name'] + '":\n')
            else:
                file.write('                    ' + ifelse + 'if linecell[0] in ' + repr(tuple(accepted_names)) + ':\n')
            if option['name'] == 'user_data':
                file.write('                        full_notes = line[len("user_data"):].lstrip(" ").rstrip(" \\r\\n")\n')
                file.write('                        self.user_data = _parse_user_data(full_notes) if full_notes.strip() else {}\n')
            elif option['name'] == 'spice_utility_extension':    
                file.write('                        if len(linecell) > 1:\n')
                file.write('                            self.' + option['name'] + ' = ' + converter_in + 'linecell[1]' + converter_out + '\n')
                file.write('                        else:\n')
                file.write('                            self.' + option['name'] + ' = ""\n')
                
            else:
                if length == 1:
                    file.write('                        self.' + option['name'] + ' = ' + converter_in + 'linecell[1]' + converter_out + '\n')
                else:
                    file.write('                        self.' + option['name'] + ' = [' + converter_in + 'entry' + converter_out + ' for entry in linecell[1:]]\n')
                if option['name'] == 'mission_type':
                    file.write('                        # Check for mission types that are not supported in PyEMTG\n')
                    file.write('                        if (self.mission_type < 2): print("WARNING: The selected options file contains an unsupported mission type. The supported mission types are MGALT, FBLT, PSBI, PSFB, MGAnDSMs, CoastPhase, SundmanCoastPhase, variable phase type, ProbeEntryPhase, and ControlLawThrustPhase. Please select one of these types from the Global Mission Options tab.")\n')
            if (option['name'] == 'SPICE_high_fidelity_derivatives'
                    or (option['name'] in adaptive_integrator_options and option['name'] != 'integrator_tolerance')):
                file.write('\n')
            else:
                file.write('                  \n')
            ifelse = 'el'

        
        file.write('                    elif linecell[0] == "BEGIN_JOURNEY":\n')
        file.write('                        self.Journeys.append(JourneyOptions.JourneyOptions(inputFile, lineNumber))\n')
        file.write('        \n')
        file.write('        self.number_of_journeys = len(self.Journeys)\n')
        file.write('        \n')

        file.write('        for journeyIndex in range(0, len(self.Journeys)):\n')
        file.write('            self.Journeys[journeyIndex].universe_folder = self.universe_folder\n')
        file.write('        \n')
        file.write('        self.ConvertDecisionVector()\n')
        file.write('        self.AssembleMasterDecisionVector()\n')
        file.write('        self.AssembleMasterConstraintVectors()\n')
        file.write('        \n')

        file.write('    #************************************************************************************write\n')
        file.write('    def write_options_file(self, optionsFileName, writeAll = False):\n')
        file.write('        \n')
        file.write('        #Disassemble the master constraint and decision vectors, just in case we modified them. We want any changes to be reflected at the Journey level.\n')
        file.write('        self.DisassembleMasterDecisionVector()\n')
        file.write('        self.DisassembleMasterConstraintVectors()\n')
        file.write('        \n')
        file.write('        with open(optionsFileName, "w+") as optionsFile:\n')
        file.write('            optionsFile.write("#EMTGv9 .emtgopt file version 2\\n")\n')
        file.write('            optionsFile.write("\\n")\n')
        file.write('            \n')

        for option in OptionsDefinitions:
            name = option['name']

            if name == 'user_data':
                file.write('            optionsFile.write("\\n#Enter any user data that should be appended to the .emtg file.\\n")\n')
                file.write('            optionsFile.write("#This is typically used in python wrappers\\n")\n')
                file.write('            optionsFile.write("user_data ")\n')
                file.write('            first_entry = True\n')
                file.write('            for entry in self.user_data.keys():\n')
                file.write('                if first_entry == True:\n')
                file.write('                    first_entry = False\n')
                file.write('                else:\n')
                file.write('                    optionsFile.write(":")\n')
                file.write('                optionsFile.write(\'("\' + entry + \'",\')\n')
                file.write('                if isinstance(self.user_data[entry],str):\n')
                file.write('                    optionsFile.write("\'" + str(self.user_data[entry]) + "\')") \n')
                file.write('                else:\n')
                file.write('                    optionsFile.write(str(self.user_data[entry]) + ")")\n')
                file.write('            optionsFile.write("\\n")\n')
                file.write('            optionsFile.write("\\n")\n')

            elif name == 'print_only_non_default_options':
                file.write('            # Always output the non-default printing option\n')
                file.write('            optionsFile.write("#' + option['description'] + '\\n")\n')
                file.write('            optionsFile.write("' + name + ' " + str(int(self.' + name + ')) + "\\n")\n')
                file.write('            optionsFile.write("\\n")\n')

            else:
                defaultValue = ''
                if option['dataType'] == 'std::string':
                    defaultValue = '"' + str(option['defaultValue']) + '"'
                else:
                    defaultValue = str(option['defaultValue'])

                file.write('            if (self.' + name + ' != ' + defaultValue + ' or writeAll):\n')
                file.write('                optionsFile.write("#' + option['description'] + '\\n")\n')
                if 'std::vector' in option['dataType']:
                    elementType = option['dataType'].replace('std::vector<','').replace('>','')
                    file.write('                optionsFile.write("' + name + '")\n')
                    file.write('                for entry in self.' + name + ':\n')
                    if 'bool' in option['dataType']:
                        file.write('                    optionsFile.write(" " + str(int(entry)))\n')
                    else:
                        file.write('                    optionsFile.write(" " + str(entry))\n')
                    file.write('                optionsFile.write("\\n")\n')
                else:
                    if 'bool' in option['dataType']:
                        file.write('                optionsFile.write("' + name + ' " + str(int(self.' + name + ')) + "\\n")\n')
                    else:
                        file.write('                optionsFile.write("' + name + ' " + str(self.' + name + ') + "\\n")\n')
                if (name == 'SPICE_high_fidelity_derivatives'
                        or (name in adaptive_integrator_options and name not in {'integratorType', 'integrator_tolerance'})):
                    file.write('\n')
                else:
                    file.write('    \n')
        
        file.write('            \n')
        file.write('            optionsFile.close()\n')
        file.write('            \n')
        file.write('            for Journey in self.Journeys:\n')
        file.write('                Journey.write(optionsFileName, writeAll)\n')
        file.write('            \n') 

        
        file.write('    #************************************************************************************convert decision vector\n')
        file.write('    def ConvertDecisionVector(self):\n')
        file.write('        for Journey in self.Journeys:\n')
        file.write('            Journey.ConvertDecisionVector(self.ParallelShootingStateRepresentation, self.PeriapseBoundaryStateRepresentation)\n')
        file.write('        \n')
        
        
        file.write('    #************************************************************************************assemble master decision vector\n')
        file.write('    def AssembleMasterDecisionVector(self):\n')
        file.write('        self.trialX = []\n')
        file.write('        for journeyIndex in range(0, len(self.Journeys)):\n')
        file.write('            for entry in self.Journeys[journeyIndex].trialX:\n')
        file.write('                self.trialX.append(["j" + str(journeyIndex) + entry[0], entry[1]])\n')
        file.write('        \n')

        file.write('    #************************************************************************************assemble master constraint vectors\n')
        file.write('    def AssembleMasterConstraintVectors(self):\n')
        file.write('        self.ManeuverConstraintDefinitions = []\n')
        file.write('        self.BoundaryConstraintDefinitions = []\n')
        file.write('        self.PhaseDistanceConstraintDefinitions = []\n')
        file.write('        for journeyIndex in range(0, len(self.Journeys)):\n')
        file.write('            for entry in self.Journeys[journeyIndex].ManeuverConstraintDefinitions:\n')
        file.write('                if "#" in entry:\n')
        file.write('                    self.ManeuverConstraintDefinitions.append("#j" + str(journeyIndex) + entry.rstrip("\\r\\n").lstrip("#"))\n')
        file.write('                else:\n')
        file.write('                    self.ManeuverConstraintDefinitions.append("j" + str(journeyIndex) + entry.rstrip("\\r\\n"))\n')
        file.write('            for entry in self.Journeys[journeyIndex].BoundaryConstraintDefinitions:\n')
        file.write('                if "#" in entry:\n')
        file.write('                    self.BoundaryConstraintDefinitions.append("#j" + str(journeyIndex) + entry.rstrip("\\r\\n").lstrip("#"))\n')
        file.write('                else:\n')
        file.write('                    self.BoundaryConstraintDefinitions.append("j" + str(journeyIndex) + entry.rstrip("\\r\\n"))\n')
        file.write('            for entry in self.Journeys[journeyIndex].PhaseDistanceConstraintDefinitions:\n')
        file.write('                if "#" in entry:\n')
        file.write('                    self.PhaseDistanceConstraintDefinitions.append("#j" + str(journeyIndex) + entry.rstrip("\\r\\n").lstrip("#"))\n')
        file.write('                else:\n')
        file.write('                    self.PhaseDistanceConstraintDefinitions.append("j" + str(journeyIndex) + entry.rstrip("\\r\\n"))\n')
        file.write('        \n')
        
        file.write('    #************************************************************************************disassemble master decision vector\n')
        file.write('    def DisassembleMasterDecisionVector(self):\n')
        file.write('        #clear the journey trialX vectors\n')
        file.write('        for Journey in self.Journeys:\n')
        file.write('            Journey.trialX = []\n')
        file.write('        \n')
        file.write('        for entry in self.trialX:\n')
        file.write('            journeyIndex = int(entry[0][0:entry[0].find("p")].strip("j"))\n')
        file.write('            \n')
        file.write('            if journeyIndex < len(self.Journeys):\n')
        file.write('                self.Journeys[journeyIndex].trialX.append([entry[0][entry[0].find("p"):], entry[1]])\n')
        file.write('        \n')

        file.write('    #************************************************************************************disassemble master constraint vectors\n')
        file.write('    def DisassembleMasterConstraintVectors(self):\n')
        file.write('        #clear the journey constraint vectors\n')
        file.write('        for Journey in self.Journeys:\n')
        file.write('            Journey.ManeuverConstraintDefinitions = []\n')
        file.write('            Journey.BoundaryConstraintDefinitions = []\n')
        file.write('            Journey.PhaseDistanceConstraintDefinitions = []\n')
        file.write('        \n')
        file.write('        for entry in self.ManeuverConstraintDefinitions:\n')
        file.write('            if entry.rstrip("\\r\\n"):\n')
        file.write('                journeyIndex = int(entry[0:entry.find("p")].strip("#j"))\n')
        file.write('                \n')
        file.write('                commentCharacter = ""\n')
        file.write('                if "#" in entry:\n')
        file.write('                    commentCharacter = "#"\n')
        file.write('                \n')
        file.write('                if journeyIndex < len(self.Journeys):\n')
        file.write('                    self.Journeys[journeyIndex].ManeuverConstraintDefinitions.append(commentCharacter + entry[entry.find("p"):].rstrip("\\r\\n"))\n')
        file.write('            \n')
        file.write('        for entry in self.BoundaryConstraintDefinitions:\n')
        file.write('            if entry.rstrip("\\r\\n"):\n')
        file.write('                journeyIndex = int(entry[0:entry.find("p")].strip("#j"))\n')
        file.write('                \n')
        file.write('                commentCharacter = ""\n')
        file.write('                if "#" in entry:\n')
        file.write('                    commentCharacter = "#"\n')
        file.write('                \n')
        file.write('                if journeyIndex < len(self.Journeys):\n')
        file.write('                    self.Journeys[journeyIndex].BoundaryConstraintDefinitions.append(commentCharacter + entry[entry.find("p"):].rstrip("\\r\\n"))\n')
        file.write('            \n')
        file.write('        for entry in self.PhaseDistanceConstraintDefinitions:\n')
        file.write('            if entry.rstrip("\\r\\n"):\n')
        file.write('                journeyIndex = int(entry[0:entry.find("p")].strip("#j"))\n')
        file.write('                \n')
        file.write('                commentCharacter = ""\n')
        file.write('                if "#" in entry:\n')
        file.write('                    commentCharacter = "#"\n')
        file.write('                \n')
        file.write('                if journeyIndex < len(self.Journeys):\n')
        file.write('                    self.Journeys[journeyIndex].PhaseDistanceConstraintDefinitions.append(commentCharacter + entry[entry.find("p"):].rstrip("\\r\\n"))\n')
        file.write('        \n')
        file.write('        \n')
        file.write('    #************************************************************************************getJourneyIndex()\n')
        file.write('    def getJourneyIndex(self, journeyNameString):\n')
        file.write('        for journeyIndex in range(0, len(self.Journeys)):\n')
        file.write('            if self.Journeys[journeyIndex].journey_name == journeyNameString:\n')
        file.write('                return journeyIndex\n')
        file.write('        \n')
        file.write('        #if you get this far, something went wrong                                                                 \n')
        file.write('        raise Exception("Journey \'" + journeyNameString + "\' not found.")  \n')
