set(command)
set(after_separator FALSE)
math(EXPR last "${CMAKE_ARGC} - 1")
foreach(index RANGE ${last})
    set(argument "${CMAKE_ARGV${index}}")
    if(after_separator)
        # Change only source files below this LAPACK checkout. Include, module,
        # object, and compiler paths retain the build system's original values.
        if(IS_ABSOLUTE "${argument}" AND argument MATCHES "\\.[fF]([0-9]+|[oO][rR])?$")
            file(RELATIVE_PATH from_source "${SOURCE_ROOT}" "${argument}")
            if(NOT from_source MATCHES "^\\.\\./" AND NOT IS_ABSOLUTE "${from_source}")
                file(RELATIVE_PATH argument "${CMAKE_CURRENT_BINARY_DIR}" "${argument}")
            endif()
        endif()
        list(APPEND command "${argument}")
    elseif(argument STREQUAL "--")
        set(after_separator TRUE)
    endif()
endforeach()
if(NOT command)
    message(FATAL_ERROR "Fortran launcher requires a compiler command after --")
endif()
execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "Fortran compilation failed (${result})")
endif()
